#pragma once
#include "Bridge/CompatibilityCatalog.h"
namespace Win32Bridge { namespace Bridge {
LSTATUS WINAPI BridgeRegOpenKeyExW(HKEY,LPCWSTR,DWORD,REGSAM,PHKEY);
LSTATUS WINAPI BridgeRegCreateKeyExW(HKEY,LPCWSTR,DWORD,LPWSTR,DWORD,REGSAM,LPSECURITY_ATTRIBUTES,PHKEY,LPDWORD);
LSTATUS WINAPI BridgeRegQueryValueExW(HKEY,LPCWSTR,LPDWORD,LPDWORD,LPBYTE,LPDWORD);
LSTATUS WINAPI BridgeRegSetValueExW(HKEY,LPCWSTR,DWORD,DWORD,const BYTE*,DWORD);
LSTATUS WINAPI BridgeRegCloseKey(HKEY);
LSTATUS WINAPI BridgeRegDeleteValueW(HKEY,LPCWSTR);
LSTATUS WINAPI BridgeRegDeleteKeyW(HKEY,LPCWSTR);
LSTATUS WINAPI BridgeRegEnumKeyExW(HKEY,DWORD,LPWSTR,LPDWORD,LPDWORD,LPWSTR,LPDWORD,PFILETIME);
LSTATUS WINAPI BridgeRegOpenKeyExA(HKEY,LPCSTR,DWORD,REGSAM,PHKEY);
LSTATUS WINAPI BridgeRegCreateKeyExA(HKEY,LPCSTR,DWORD,LPSTR,DWORD,REGSAM,LPSECURITY_ATTRIBUTES,PHKEY,LPDWORD);
LSTATUS WINAPI BridgeRegQueryValueExA(HKEY,LPCSTR,LPDWORD,LPDWORD,LPBYTE,LPDWORD);
LSTATUS WINAPI BridgeRegSetValueExA(HKEY,LPCSTR,DWORD,DWORD,const BYTE*,DWORD);
LSTATUS WINAPI BridgeRegDeleteValueA(HKEY,LPCSTR);
LSTATUS WINAPI BridgeRegDeleteKeyA(HKEY,LPCSTR);
BOOL WINAPI BridgeLookupPrivilegeValueW(LPCWSTR,LPCWSTR,PLUID);
BOOL WINAPI BridgeOpenProcessToken(HANDLE,DWORD,PHANDLE);
BOOL WINAPI BridgeAdjustTokenPrivileges(HANDLE,BOOL,PTOKEN_PRIVILEGES,DWORD,PTOKEN_PRIVILEGES,PDWORD);
BOOL WINAPI BridgeGetFileSecurityW(LPCWSTR,SECURITY_INFORMATION,PSECURITY_DESCRIPTOR,DWORD,LPDWORD);
BOOL WINAPI BridgeSetFileSecurityW(LPCWSTR,SECURITY_INFORMATION,PSECURITY_DESCRIPTOR);
LSTATUS WINAPI BridgeRegDeleteKeyExW(HKEY,LPCWSTR,REGSAM,DWORD);
BOOL WINAPI BridgeGetUserNameW(LPWSTR,LPDWORD);
BOOL WINAPI BridgeLookupAccountNameW(LPCWSTR,LPCWSTR,PSID,LPDWORD,LPWSTR,LPDWORD,PSID_NAME_USE);
LONG WINAPI BridgeLsaOpenPolicy(PVOID,PVOID,ACCESS_MASK,PVOID);
LONG WINAPI BridgeLsaAddAccountRights(ULONG_PTR,PSID,PVOID,ULONG);
LONG WINAPI BridgeLsaClose(ULONG_PTR);
BOOLEAN WINAPI BridgeSystemFunction036(PVOID buffer, ULONG length);
ImportResolution ResolveAdvapi32Import(const ImportedSymbol&);
} }
