#include "pch.h"
#include "Bridge/GuestRegistry.h"
using namespace Win32Bridge::Bridge;
namespace { thread_local GuestRegistryContext* g_registry=nullptr; void E(DWORD* e,DWORD v){if(e)*e=v;} }
std::wstring GuestRegistryContext::Normalize(LPCWSTR s){ std::wstring v=s?s:L""; for(auto& c:v){if(c==L'/')c=L'\\'; c=(wchar_t)towlower(c);} return v; }
bool GuestRegistryContext::Resolve(HKEY h,std::wstring* p,DWORD* e) const { if(h==HKEY_CURRENT_USER){*p=L"hkcu";return true;} if(h==HKEY_LOCAL_MACHINE){*p=L"hklm";return true;} auto i=m_handles.find((ULONG_PTR)h);if(i==m_handles.end()){E(e,ERROR_INVALID_HANDLE);return false;}*p=i->second;return true; }
bool GuestRegistryContext::OpenKey(HKEY h,LPCWSTR s,REGSAM,HKEY* r,DWORD* e){std::lock_guard<std::mutex>g(m_lock);std::wstring p;if(!r||!Resolve(h,&p,e))return false;p+=L"\\"+Normalize(s);if(!m_keys.count(p)){E(e,ERROR_FILE_NOT_FOUND);return false;}*r=(HKEY)m_nextHandle;m_handles[m_nextHandle++]=p;E(e,0);return true;}
bool GuestRegistryContext::CreateKey(HKEY h,LPCWSTR s,REGSAM a,HKEY* r,DWORD*d,DWORD*e){std::lock_guard<std::mutex>g(m_lock);std::wstring p;if(!r||!Resolve(h,&p,e))return false;p+=L"\\"+Normalize(s);bool n=!m_keys.count(p);m_keys[p].path=p;if(d)*d=n?REG_CREATED_NEW_KEY:REG_OPENED_EXISTING_KEY;*r=(HKEY)m_nextHandle;m_handles[m_nextHandle++]=p;E(e,0);return true;}
bool GuestRegistryContext::QueryValue(HKEY h,LPCWSTR n,LPDWORD t,LPBYTE d,LPDWORD b,DWORD*e) const{std::lock_guard<std::mutex>g(m_lock);std::wstring p;if(!b||!Resolve(h,&p,e))return false;auto k=m_keys.find(p);if(k==m_keys.end()){E(e,ERROR_FILE_NOT_FOUND);return false;}auto v=k->second.values.find(Normalize(n));if(v==k->second.values.end()){E(e,ERROR_FILE_NOT_FOUND);return false;}if(t)*t=v->second.type;DWORD need=(DWORD)v->second.data.size();if(!d){*b=need;E(e,ERROR_SUCCESS);return true;}if(*b<need){*b=need;E(e,ERROR_MORE_DATA);return false;}memcpy(d,v->second.data.data(),need);*b=need;E(e,0);return true;}
bool GuestRegistryContext::SetValue(HKEY h,LPCWSTR n,DWORD t,const BYTE*d,DWORD b,DWORD*e){std::lock_guard<std::mutex>g(m_lock);std::wstring p;if((b&&!d)||!Resolve(h,&p,e))return false;auto k=m_keys.find(p);if(k==m_keys.end()){E(e,ERROR_FILE_NOT_FOUND);return false;}Value v;v.type=t;if(b)v.data.assign(d,d+b);k->second.values[Normalize(n)]=std::move(v);E(e,0);return true;}
bool GuestRegistryContext::CloseKey(HKEY h,DWORD*e){std::lock_guard<std::mutex>g(m_lock);auto i=m_handles.find((ULONG_PTR)h);if(i==m_handles.end()){E(e,ERROR_INVALID_HANDLE);return false;}m_handles.erase(i);E(e,0);return true;}
bool GuestRegistryContext::DeleteValue(HKEY h,LPCWSTR n,DWORD*e){std::lock_guard<std::mutex>g(m_lock);std::wstring p;if(!Resolve(h,&p,e))return false;auto k=m_keys.find(p);if(k==m_keys.end()||k->second.values.erase(Normalize(n))==0){E(e,ERROR_FILE_NOT_FOUND);return false;}E(e,0);return true;}
bool GuestRegistryContext::DeleteKey(HKEY h,LPCWSTR s,DWORD*e){std::lock_guard<std::mutex>g(m_lock);std::wstring p;if(!Resolve(h,&p,e))return false;p+=L"\\"+Normalize(s);for(const auto&x:m_keys)if(x.first.size()>p.size()&&x.first.compare(0,p.size(),p)==0&&x.first[p.size()]==L'\\'){E(e,ERROR_ACCESS_DENIED);return false;}if(m_keys.erase(p)==0){E(e,ERROR_FILE_NOT_FOUND);return false;}E(e,0);return true;}
bool GuestRegistryContext::EnumKey(HKEY h,DWORD i,LPWSTR n,LPDWORD c,DWORD*e)const{std::lock_guard<std::mutex>g(m_lock);std::wstring p;if(!c||!Resolve(h,&p,e))return false;std::vector<std::wstring> names;for(const auto&x:m_keys){if(x.first.rfind(p+L"\\",0)!=0)continue;auto r=x.first.substr(p.size()+1);if(r.find(L'\\')==std::wstring::npos)names.push_back(r);}if(i>=names.size()){E(e,ERROR_NO_MORE_ITEMS);return false;}DWORD need=(DWORD)names[i].size();if(!n||*c<=need){*c=need;E(e,ERROR_MORE_DATA);return false;}memcpy(n,names[i].c_str(),(need+1)*sizeof(wchar_t));*c=need;E(e,0);return true;}
GuestRegistryContext* Win32Bridge::Bridge::CurrentGuestRegistryContext(){return g_registry;}
GuestRegistryScope::GuestRegistryScope(GuestRegistryContext*v):m_previous(g_registry){g_registry=v;}
GuestRegistryScope::~GuestRegistryScope(){g_registry=m_previous;}
