#include "pch.h"
#include "Bridge/OleShims.h"
#include "Bridge/RuntimeDiagnostics.h"
using namespace Win32Bridge::Bridge;
namespace { thread_local unsigned c=0; bool L(const std::wstring&s,const wchar_t*n){return _wcsicmp(s.c_str(),n)==0;} }
HRESULT WINAPI Win32Bridge::Bridge::BridgeCoInitialize(LPVOID){++c;return c==1?S_OK:S_FALSE;} HRESULT WINAPI Win32Bridge::Bridge::BridgeOleInitialize(LPVOID p){return BridgeCoInitialize(p);} void WINAPI Win32Bridge::Bridge::BridgeCoUninitialize(){if(c)--c;} void WINAPI Win32Bridge::Bridge::BridgeOleUninitialize(){BridgeCoUninitialize();}
LPVOID WINAPI Win32Bridge::Bridge::BridgeCoTaskMemAlloc(SIZE_T n){return ::CoTaskMemAlloc(n);} void WINAPI Win32Bridge::Bridge::BridgeCoTaskMemFree(LPVOID p){::CoTaskMemFree(p);} HRESULT WINAPI Win32Bridge::Bridge::BridgeCoCreateInstance(REFCLSID clsid,LPUNKNOWN,DWORD,REFIID iid,LPVOID*o){if(o)*o=nullptr;wchar_t line[256]={};swprintf_s(line,L"COM: CoCreateInstance requested class {%08lX-%04hX-%04hX-%02hhX%02hhX-%02hhX%02hhX%02hhX%02hhX%02hhX%02hhX}; IID {%08lX-%04hX-%04hX-%02hhX%02hhX-%02hhX%02hhX%02hhX%02hhX%02hhX%02hhX} is not registered.",clsid.Data1,clsid.Data2,clsid.Data3,clsid.Data4[0],clsid.Data4[1],clsid.Data4[2],clsid.Data4[3],clsid.Data4[4],clsid.Data4[5],clsid.Data4[6],clsid.Data4[7],iid.Data1,iid.Data2,iid.Data3,iid.Data4[0],iid.Data4[1],iid.Data4[2],iid.Data4[3],iid.Data4[4],iid.Data4[5],iid.Data4[6],iid.Data4[7]);RuntimeDiagnostics::Record(line);return REGDB_E_CLASSNOTREG;}
void WINAPI Win32Bridge::Bridge::BridgeReleaseStgMedium(PVOID){} HRESULT WINAPI Win32Bridge::Bridge::BridgeRegisterDragDrop(HWND,PVOID){return E_NOTIMPL;} HRESULT WINAPI Win32Bridge::Bridge::BridgeRevokeDragDrop(HWND){return E_NOTIMPL;} HRESULT WINAPI Win32Bridge::Bridge::BridgeDoDragDrop(PVOID,PVOID,DWORD,DWORD*effect){if(effect)*effect=0;return E_NOTIMPL;}
BSTR WINAPI Win32Bridge::Bridge::BridgeSysAllocString(LPCOLESTR s){return ::SysAllocString(s);} BSTR WINAPI Win32Bridge::Bridge::BridgeSysAllocStringLen(const OLECHAR*s,UINT n){return ::SysAllocStringLen(s,n);} void WINAPI Win32Bridge::Bridge::BridgeSysFreeString(BSTR s){::SysFreeString(s);} UINT WINAPI Win32Bridge::Bridge::BridgeSysStringLen(BSTR s){return ::SysStringLen(s);} UINT WINAPI Win32Bridge::Bridge::BridgeSysStringByteLen(BSTR s){return ::SysStringByteLen(s);} HRESULT WINAPI Win32Bridge::Bridge::BridgeVariantClear(VARIANTARG*v){return v?::VariantClear(v):E_INVALIDARG;} HRESULT WINAPI Win32Bridge::Bridge::BridgeVariantCopy(VARIANTARG*d,const VARIANTARG*s){return d&&s?::VariantCopy(d,s):E_INVALIDARG;}
ImportResolution Win32Bridge::Bridge::ResolveOleImport(const ImportedSymbol&s){auto r=CompatibilityCatalog::Resolve(s);if(L(s.library,L"ole32.dll")){if(L(s.name,L"coinitialize"))r.targetAddress=(ULONGLONG)&BridgeCoInitialize;else if(L(s.name,L"oleinitialize"))r.targetAddress=(ULONGLONG)&BridgeOleInitialize;else if(L(s.name,L"couninitialize"))r.targetAddress=(ULONGLONG)&BridgeCoUninitialize;else if(L(s.name,L"oleuninitialize"))r.targetAddress=(ULONGLONG)&BridgeOleUninitialize;else if(L(s.name,L"cotaskmemalloc"))r.targetAddress=(ULONGLONG)&BridgeCoTaskMemAlloc;else if(L(s.name,L"cotaskmemfree"))r.targetAddress=(ULONGLONG)&BridgeCoTaskMemFree;else if(L(s.name,L"cocreateinstance"))r.targetAddress=(ULONGLONG)&BridgeCoCreateInstance;else if(L(s.name,L"releasestgmedium"))r.targetAddress=(ULONGLONG)&BridgeReleaseStgMedium;else if(L(s.name,L"registerdragdrop"))r.targetAddress=(ULONGLONG)&BridgeRegisterDragDrop;else if(L(s.name,L"revokedragdrop"))r.targetAddress=(ULONGLONG)&BridgeRevokeDragDrop;else if(L(s.name,L"dodragdrop"))r.targetAddress=(ULONGLONG)&BridgeDoDragDrop;}else if(L(s.library,L"oleaut32.dll")&&s.importedByOrdinal){switch(s.ordinal){case 2:r.targetAddress=(ULONGLONG)&BridgeSysAllocString;break;case 4:r.targetAddress=(ULONGLONG)&BridgeSysAllocStringLen;break;case 6:r.targetAddress=(ULONGLONG)&BridgeSysFreeString;break;case 7:r.targetAddress=(ULONGLONG)&BridgeSysStringLen;break;case 9:r.targetAddress=(ULONGLONG)&BridgeVariantClear;break;case 10:r.targetAddress=(ULONGLONG)&BridgeVariantCopy;break;case 149:case 150:r.targetAddress=(ULONGLONG)&BridgeSysStringByteLen;break;}}if(r.targetAddress)r.disposition=ImportDisposition::NeedsBridge;return r;}
