import "inspectable.idl";

namespace DesktopMode.Gecko
{
    runtimeclass GeckoHost
    {
        GeckoHost();

        Object Content{ get; };
        Boolean IsStarted{ get; };

        void Start(Double width, Double height);
        void SetViewport(Double width, Double height);
        void SetScreen(Double width, Double height);
        void SetActive(Boolean active);
        Int32 TakeWindowCommand();
        void OpenUrl(String url);
        void Suspend();
        void Resume();
    }
}
